name: Run Rust Tests

on:
  push: 
    branches:
      - main
  workflow_call:

permissions:
  contents: read

env:
  RUST_TARGET: riscv32imc-esp-espidf

jobs:
  rust-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cargo-bins/cargo-binstall@main
        
      - name: Install espup and esp32 toolchain
        run: |
          cargo binstall espup
          espup install

      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
          cargo install --locked ldproxy
      
      - name: Compile Tests
        run: cargo build --tests --workspace --target ${{ env.RUST_TARGET }}
